
-- Insert news articles related to finance and banking in Angola
INSERT INTO news (slug, title, subtitle, body_html, categories, tags, publication_date, author, is_featured, social_links, created_at, updated_at)
VALUES
  ('nova-regulamentacao-bancaria-angola', 'Nova Regulamentação Bancária em Angola', 'Banco Nacional de Angola anuncia mudanças importantes', '<p>O Banco Nacional de Angola (BNA) anunciou hoje um novo conjunto de regulamentações destinadas a fortalecer o setor bancário do país e a alinhar as práticas locais com os padrões internacionais. As medidas incluem requisitos de capital mais rigorosos, novas diretrizes de governança corporativa e um foco renovado na transformação digital.</p><p>Segundo o governador do BNA, as mudanças são cruciais para garantir a estabilidade financeira e aumentar a confiança dos investidores internacionais. "Estamos a construir um setor bancário mais resiliente, transparente e inovador", afirmou ele numa conferência de imprensa em Luanda.</p><p>As novas regras entrarão em vigor progressivamente ao longo dos próximos 18 meses, dando tempo aos bancos para se adaptarem.</p>', 'Regulamentação', 'banco,regulamentação,angola', '2025-09-20T08:00:00Z', 'Redação Ser Bancário', 1, '["https://twitter.com/serbancario", "https://www.linkedin.com/company/serbancario"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('tendencias-banca-digital-angola-2025', 'Tendências da Banca Digital em Angola 2025', 'Como a tecnologia está transformando o setor financeiro', '<p>A transformação digital está a impulsionar a inovação no setor bancário angolano, com a adoção crescente de mobile banking, pagamentos digitais e fintechs locais. Este artigo explora as principais tendências tecnológicas que estão a moldar o futuro da banca em Angola.</p><p>Além disso, destacamos os desafios de cibersegurança e a importância da inclusão financeira para expandir o acesso aos serviços bancários.</p><img src="https://heyboss.heeyo.ai/1758894992-396fa840.webp" alt="Banca Digital Angola" />', 'Tecnologia', 'fintech,banca digital,angola', '2025-09-22T10:30:00Z', 'João Silva', 0, '["https://facebook.com/serbancario", "https://instagram.com/serbancario"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('crescimento-fintech-angola', 'Crescimento das Fintechs em Angola', 'Startups que estão revolucionando o setor financeiro', '<p>O ecossistema fintech em Angola tem crescido rapidamente, oferecendo soluções inovadoras para pagamentos, crédito e investimentos. Este crescimento está a atrair investimentos nacionais e internacionais, impulsionando a competitividade do setor bancário tradicional.</p><p>Conheça as principais fintechs que estão a liderar essa transformação e os impactos esperados para os consumidores angolanos.</p>', 'Inovação', 'fintech,startups,investimento', '2025-09-24T09:00:00Z', 'Ana Rodrigues', 0, '["https://linkedin.com/company/fintech-angola"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('impacto-inclusao-financeira', 'Impacto da Inclusão Financeira no Desenvolvimento Econômico de Angola', 'A importância de ampliar o acesso aos serviços bancários', '<p>A inclusão financeira é um dos pilares para o desenvolvimento sustentável em Angola. Este artigo analisa como a ampliação do acesso aos serviços bancários pode contribuir para a redução da pobreza e o fortalecimento da economia local.</p><p>Destacamos programas governamentais e iniciativas privadas que visam aumentar a penetração bancária em áreas rurais e populações vulneráveis.</p>', 'Economia', 'inclusao financeira,desenvolvimento,angola', '2025-09-25T11:00:00Z', 'Carlos Mendes', 0, '[]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
