
-- Insert blog posts related to finance and banking in Angola
INSERT INTO blogposts (slug, title, subtitle, body_html, categories, tags, publication_date, author, social_links, created_at, updated_at)
VALUES
  ('futuro-banca-digital-angola', 'O Futuro da Banca Digital em Angola', 'Análise das tendências tecnológicas que moldam o setor', '<p>A transformação digital está a redefinir o setor bancário em Angola a um ritmo sem precedentes. Este artigo explora as principais tendências, desde a adoção de mobile banking até o surgimento de fintechs inovadoras, e analisa como as instituições tradicionais estão a responder a este novo paradigma.</p><p>Discutimos o papel da inteligência artificial na personalização de serviços, a importância da cibersegurança num mundo cada vez mais conectado e os desafios regulatórios que acompanham a inovação.</p>', 'Análise', 'banca digital,tecnologia,fintech', '2025-09-21T09:00:00Z', 'Maria Santos', '["https://twitter.com/mariasantos"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('inclusao-financeira-desafios', 'Inclusão Financeira: Desafios e Oportunidades', 'Como expandir o acesso aos serviços bancários', '<p>A inclusão financeira é uma prioridade para o desenvolvimento econômico de Angola. Este post discute os principais desafios enfrentados para ampliar o acesso aos serviços bancários e as oportunidades que surgem com a digitalização dos serviços financeiros.</p>', 'Opinião', 'inclusao financeira,desenvolvimento,angola', '2025-09-23T14:00:00Z', 'Carlos Mendes', '[]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('fintechs-angolanas-crescimento', 'Fintechs Angolanas: O Ecossistema em Crescimento', 'Startups que estão revolucionando o setor financeiro', '<p>O setor fintech em Angola está em expansão, com várias startups oferecendo soluções inovadoras para pagamentos, crédito e investimentos. Este post analisa o impacto dessas empresas no mercado financeiro local e as perspectivas para o futuro.</p>', 'Inovação', 'fintech,startups,angola', '2025-09-24T16:30:00Z', 'Ana Rodrigues', '["https://linkedin.com/in/anarodrigues"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
